---
title: "Interesting Forecasting Applications with R"
author: "Suleyman Turancan Burucu - IE360 - Fall 2020"
---
```{r,echo=FALSE,results="hide"}
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)

```

<h3>1. [Time series forecasting using ARIMA models](https://blogs.oracle.com/datascience/introduction-to-forecasting-with-arima-in-r)</h3>

    >This example is important because it introduces the forecasting methodology using ***ARIMA models*** in R. The steps are:
    
    <p>+ **Load R Packages**
    + **Examine Your Data**
    + **Decompose Your Data**
    + **Stationarity**
    + **Autocorrelations and Choosing Model Order**
    + **Fitting an ARIMA model**
    + **Evaluate and Iterate**</p>
  
    <p>Finally, we will reach an ARIMA model while those steps are traced.</p>

<h3>2. [Time series forecasting using AR models](https://machinelearningmastery.com/time-series-forecasting-methods-in-python-cheat-sheet/)</h3>
    
    >The ***autoregression (AR) method*** models the next step in the sequence as a linear function of the observations at prior time steps.

    The notation for the model involves specifying the order of the model p as a parameter to the AR function, e.g. AR(p). For example, AR(1) is a first-order autoregression model.
    
    The method is suitable for univariate time series without trend and seasonal components.

<h3>3. [Time series forecasting using MA models](https://machinelearningmastery.com/time-series-forecasting-methods-in-python-cheat-sheet/)</h3>

    >The ***moving average (MA) method*** models the next step in the sequence as a linear function  of the residual errors from a mean process at prior time steps.

    A moving average model is different from calculating the moving average of the time series.

    The notation for the model involves specifying the order of the model q as a parameter to the MA function, e.g. MA(q). For example, MA(1) is a first-order moving average model.

    The method is suitable for univariate time series without trend and seasonal components.

<h3>4. [Time series forecasting using ARMA models](https://machinelearningmastery.com/time-series-forecasting-methods-in-python-cheat-sheet/)</h3>

    >The ***Autoregressive Moving Average (ARMA) method*** models the next step in the sequence as a     linear function of the observations and resiudal errors at prior time steps.

    It combines both Autoregression (AR) and Moving Average (MA) models.

    The notation for the model involves specifying the order for the AR(p) and MA(q) models as parameters to an ARMA function, e.g. ARMA(p, q). An ARIMA model can be used to develop AR or MA models.

    The method is suitable for univariate time series without trend and seasonal components.
    
<h3>5. [Time series forecasting using SARIMA models](https://machinelearningmastery.com/time-series-forecasting-methods-in-python-cheat-sheet/)</h3>

    >The ***Seasonal Autoregressive Integrated Moving Average (SARIMA) method*** models the next step in the sequence as a linear function of the differenced observations, errors, differenced seasonal observations, and seasonal errors at prior time steps.

    It combines the ARIMA model with the ability to perform the same autoregression, differencing, and moving average modeling at the seasonal level.

    The notation for the model involves specifying the order for the AR(p), I(d), and MA(q) models as parameters to an ARIMA function and AR(P), I(D), MA(Q) and m parameters at the seasonal level, e.g. SARIMA(p, d, q)(P, D, Q)m where “m” is the number of time steps in each season (the seasonal period). A SARIMA model can be used to develop AR, MA, ARMA and ARIMA models.

    The method is suitable for univariate time series with trend and/or seasonal components.



